# Generated by Django 5.2.11 on 2026-04-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено')], default='pending', max_length=10, verbose_name='Статус')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая сумма')),
                ('attendance_days', models.IntegerField(default=0, verbose_name='Дни посещения')),
                ('total_days', models.IntegerField(default=0, verbose_name='Всего дней в месяце')),
                ('food_days', models.IntegerField(default=0, verbose_name='Дни питания')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-year', '-month'],
                'unique_together': {('child', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PaymentCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчета')),
                ('details', models.JSONField(verbose_name='Детали расчета')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Расчет платежа',
                'verbose_name_plural': 'Расчеты платежей',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('nursery', 'Ясельная (1.5-3 года)'), ('kindergarten', 'Сад (3-7 лет)')], max_length=20, verbose_name='Возрастная категория')),
                ('family_type', models.CharField(choices=[('regular', 'Менее трех детей'), ('multi_child', 'Трое и более детей')], max_length=20, verbose_name='Тип семьи')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('content_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Содержание')),
                ('food_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Питание')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-year', 'age_category'],
                'unique_together': {('age_category', 'family_type', 'year')},
            },
        ),
    ]
