# Generated by Django 5.2.11 on 2026-05-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_remove_child_parents_alter_childparent_child_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('service_type', models.CharField(choices=[('circle', 'Кружок'), ('section', 'Секция'), ('studio', 'Студия'), ('course', 'Курс')], max_length=20, verbose_name='Тип услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость в месяц')),
                ('age_min', models.IntegerField(default=3, verbose_name='Минимальный возраст')),
                ('age_max', models.IntegerField(default=7, verbose_name='Максимальный возраст')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Преподаватель')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Расписание')),
                ('program', models.TextField(blank=True, verbose_name='Программа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('max_students', models.IntegerField(default=10, verbose_name='Максимум детей')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='discount',
        ),
        migrations.AddField(
            model_name='payment',
            name='additional_services_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='payment',
            name='additional_services_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детали доп. услуг'),
        ),
        migrations.AddField(
            model_name='payment',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дневной тариф'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма льготы'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ставка льготы (0-1)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='food_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дневной тариф питания'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_from_account',
            field=models.BooleanField(default=False, verbose_name='Оплачено с лицевого счета'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дневной тариф (пребывание)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='food_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дневной тариф (питание)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Абонентская плата (месяц)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого к оплате'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='attendance_days',
            field=models.IntegerField(default=0, verbose_name='Фактические дни посещения'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая сумма (пребывание+питание)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено'), ('overdue', 'Просрочено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма (полный месяц)'),
        ),
        migrations.CreateModel(
            name='ChildAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Номер лицевого счета')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='children.child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Лицевой счет',
                'verbose_name_plural': 'Лицевые счета',
            },
        ),
        migrations.CreateModel(
            name='ServiceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Дата подачи')),
                ('start_date', models.DateField(verbose_name='Дата начала занятий')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Зачислен'), ('rejected', 'Отказано'), ('completed', 'Завершено'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_enrollments', to='children.child', verbose_name='Ребенок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.additionalservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись на услугу',
                'verbose_name_plural': 'Записи на услуги',
                'ordering': ['-enrollment_date'],
                'unique_together': {('child', 'service', 'start_date')},
            },
        ),
    ]
