# Generated by Django 5.2.11 on 2026-05-02 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_remove_child_parents_alter_childparent_child_and_more'),
        ('payments', '0002_additionalservice_remove_payment_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='price_per_lesson',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Стоимость одного занятия'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='schedule_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детали расписания'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='teacher_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_services', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель (пользователь)'),
        ),
        migrations.AddField(
            model_name='serviceenrollment',
            name='contract_signed',
            field=models.BooleanField(default=False, verbose_name='Договор подписан'),
        ),
        migrations.AddField(
            model_name='serviceenrollment',
            name='contract_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания договора'),
        ),
        migrations.CreateModel(
            name='GroupServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.group', verbose_name='Группа')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.additionalservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Назначение кружка группе',
                'verbose_name_plural': 'Назначения кружков группам',
                'unique_together': {('group', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ServiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('sick', 'Болезнь'), ('vacation', 'Отпуск'), ('family_reasons', 'Семейные обстоятельства')], default='present', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='payments.serviceenrollment', verbose_name='Запись')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отметил')),
            ],
            options={
                'verbose_name': 'Посещаемость занятия',
                'verbose_name_plural': 'Посещаемость занятий',
                'ordering': ['-date'],
                'unique_together': {('enrollment', 'date')},
            },
        ),
    ]
