# Generated by Django 5.2.11 on 2026-05-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_bankcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_from_account',
        ),
        migrations.AlterField(
            model_name='payment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_days',
            field=models.IntegerField(default=0, verbose_name='Всего рабочих дней в месяце'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
