# Generated by Django 5.2.11 on 2026-05-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='monthly_fee',
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='price_per_lesson',
            field=models.DecimalField(decimal_places=2, default=450, max_digits=10, verbose_name='Стоимость одного занятия'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость в месяц (полная)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='attendance_days',
            field=models.IntegerField(default=0, verbose_name='Фактические дни посещения сада'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая сумма (сад + питание)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дневной тариф (содержание)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма компенсации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ставка компенсации (0-1)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='food_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дневной тариф (питание)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='content_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Абонентская плата (содержание)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дневной тариф (содержание)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='food_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма за месяц'),
        ),
    ]
