# Generated by Django 5.2.11 on 2026-05-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_tariff_monthly_fee_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
    state_operations=[
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('age_category', 'year')},
        ),
    ],
    database_operations=[
        migrations.RunSQL(
            sql=[
                # 1. Безопасно удаляем старое ограничение, если оно есть
                "ALTER TABLE payments_tariff DROP CONSTRAINT IF EXISTS payments_tariff_age_category_family_type_year_uniq;",
                "ALTER TABLE payments_tariff DROP CONSTRAINT IF EXISTS payments_tariff_age_category_family_type_year_key;",
                
                # 2. Удаляем дубликаты - оставляем только одну запись для каждой пары (age_category, year)
                # (сохраняется запись с минимальным id, остальные удаляются)
                """
                DELETE FROM payments_tariff
                WHERE id NOT IN (
                    SELECT MIN(id)
                    FROM payments_tariff
                    GROUP BY age_category, year
                );
                """,
                
                # 3. Создаем новое ограничение уникальности
                "ALTER TABLE payments_tariff ADD CONSTRAINT payments_tariff_age_category_year_uniq UNIQUE (age_category, year);",
            ],
            reverse_sql=[
                "ALTER TABLE payments_tariff DROP CONSTRAINT IF EXISTS payments_tariff_age_category_year_uniq;",
            ],
        ),
    ],
),
        
        migrations.RemoveField(
            model_name='tariff',
            name='family_type',
        ),
    ]
