# Generated by Django 5.2.11 on 2026-04-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_add_queue_and_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('nursery_1_2', 'Ясельная (1-2 года)'), ('nursery_2_3', 'Ясельная (2-3 года)'), ('junior_3_4', 'Младшая (3-4 года)'), ('middle_4_5', 'Средняя (4-5 лет)'), ('senior_5_6', 'Старшая (5-6 лет)'), ('preparatory_6_7', 'Подготовительная (6-7 лет)')], max_length=20, unique=True, verbose_name='Возрастная категория')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Вместимость группы')),
                ('current_enrolled', models.PositiveIntegerField(default=0, verbose_name='Текущее количество зачисленных')),
                ('waiting_list', models.PositiveIntegerField(default=0, verbose_name='Количество в очереди')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка очереди',
                'verbose_name_plural': 'Настройки очереди',
            },
        ),
        migrations.AddField(
            model_name='childapplication',
            name='age_category',
            field=models.CharField(blank=True, choices=[('nursery_1_2', 'Ясельная (1-2 года)'), ('nursery_2_3', 'Ясельная (2-3 года)'), ('junior_3_4', 'Младшая (3-4 года)'), ('middle_4_5', 'Средняя (4-5 лет)'), ('senior_5_6', 'Старшая (5-6 лет)'), ('preparatory_6_7', 'Подготовительная (6-7 лет)')], max_length=20, null=True, verbose_name='Возрастная категория'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время визита для оформления'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='enrolled_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Зачислен в группу'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='enrollment_order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приказа о зачислении'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='enrollment_order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер приказа о зачислении'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='invitation_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия приглашения'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='returned_reason',
            field=models.TextField(blank=True, verbose_name='Причина возврата на доработку'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='sibling_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.childapplication', verbose_name='Заявление брата/сестры'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='sibling_in_kindergarten',
            field=models.BooleanField(default=False, verbose_name='Брат/сестра уже посещает этот детский сад'),
        ),
        migrations.AddField(
            model_name='queuehistory',
            name='age_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='queuehistory',
            name='new_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='benefit_category',
            field=models.CharField(choices=[('extraordinary', 'Внеочередное право (100 баллов)'), ('priority', 'Первоочередное право (50 баллов)'), ('preferential', 'Преимущественное право (25 баллов)'), ('none', 'Без льготы (0 баллов)')], default='none', max_length=20, verbose_name='Категория льготы'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='health_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/health_certificates/', verbose_name='Медицинская справка (оздоровительная группа)'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='legal_representative',
            field=models.TextField(blank=True, verbose_name='Данные законного представителя (если не родители)'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.parentprofile'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='queue_priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет очереди (суммарные баллы)'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='residence_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/residence_proof/', verbose_name='Подтверждение места жительства (справка)'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('queue', 'В очереди'), ('invited', 'Приглашен на оформление'), ('processing', 'На оформлении'), ('enrolled', 'Зачислен'), ('rejected', 'Отказ'), ('returned', 'Возвращено на доработку'), ('expired', 'Срок приглашения истек'), ('withdrawn', 'Отозвана')], default='draft', max_length=20, verbose_name='Статус заявления'),
        ),
        migrations.AlterField(
            model_name='queuehistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_history', to='applications.childapplication'),
        ),
        migrations.AlterField(
            model_name='queuehistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='queuehistory',
            name='new_position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='queuehistory',
            name='old_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
