# Generated by Django 5.2.11 on 2026-04-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_queuesettings_childapplication_age_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='benefit_points',
        ),
        migrations.RemoveField(
            model_name='childapplication',
            name='parent_passport_file',
        ),
        migrations.AddField(
            model_name='childapplication',
            name='benefit_document_right',
            field=models.FileField(blank=True, null=True, upload_to='applications/benefit_rights/', verbose_name='Документ о праве на льготу (внеочередное/первоочередное)'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='birth_certificate_translation',
            field=models.FileField(blank=True, null=True, upload_to='applications/birth_translations/', verbose_name='Перевод свидетельства о рождении (нотариально заверенный)'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='child_snils',
            field=models.CharField(blank=True, max_length=20, verbose_name='СНИЛС ребенка'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='foreign_residence_doc',
            field=models.FileField(blank=True, null=True, upload_to='applications/foreign_residence/', verbose_name='Документ о праве находиться в России (виза, ВНЖ, РВП)'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='guardianship_act_doc',
            field=models.FileField(blank=True, null=True, upload_to='applications/guardianship/', verbose_name='Акт о назначении опекуна'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='health_certificate_oz',
            field=models.FileField(blank=True, null=True, upload_to='applications/health_certificates/', verbose_name='Медицинская справка (оздоровительная группа)'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='is_foreign_citizen',
            field=models.BooleanField(default=False, verbose_name='Иностранный гражданин'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='is_guardianship',
            field=models.BooleanField(default=False, verbose_name='Опекунство'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/passports/', verbose_name='Паспорт родителя'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='pmpk_conclusion',
            field=models.FileField(blank=True, null=True, upload_to='applications/pmpk/', verbose_name='Заключение ПМПК (компенсирующая группа)'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='require_compensating_group',
            field=models.BooleanField(default=False, verbose_name='Требуется компенсирующая группа'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='require_health_group',
            field=models.BooleanField(default=False, verbose_name='Требуется оздоровительная группа'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='residence_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/residence_certificates/', verbose_name='Свидетельство о регистрации/справка с места жительства'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='birth_certificate_file',
            field=models.FileField(upload_to='applications/birth_certificates/', verbose_name='Свидетельство о рождении'),
        ),
    ]
