# Generated by Django 5.2.11 on 2026-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_childapplication_benefit_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childapplication',
            name='preferred_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Предпочтительная группа'),
        ),
    ]
