# Generated by Django 5.2.11 on 2026-04-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_childapplication_preferred_group'),
        ('applications', '0006_add_approved_status'),
    ]

    operations = [
    ]
