# Generated by Django 5.2.11 on 2026-04-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_merge_20260426_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('queue', 'В очереди'), ('approved', 'Одобрено'), ('invited', 'Приглашен на оформление'), ('processing', 'На оформлении'), ('enrolled', 'Зачислен'), ('rejected', 'Отказ'), ('returned', 'Возвращено на доработку'), ('expired', 'Срок приглашения истек'), ('withdrawn', 'Отозвана')], default='draft', max_length=20, verbose_name='Статус заявления'),
        ),
    ]
