# Generated by Django 5.2.11 on 2026-04-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_childapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childapplication',
            options={},
        ),
    ]
