# Generated by Django 5.2.11 on 2026-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_childapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявление', 'verbose_name_plural': 'Заявления'},
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='benefit_document_right',
            field=models.FileField(blank=True, null=True, upload_to='applications/benefit_rights/', verbose_name='Документ о праве на льготу'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='foreign_residence_doc',
            field=models.FileField(blank=True, null=True, upload_to='applications/foreign_residence/', verbose_name='Документ о праве находиться в России'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='health_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/health_certificates/', verbose_name='Медицинская справка'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='legal_representative',
            field=models.TextField(blank=True, verbose_name='Данные законного представителя'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='pmpk_conclusion',
            field=models.FileField(blank=True, null=True, upload_to='applications/pmpk/', verbose_name='Заключение ПМПК'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='queue_priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет очереди'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='residence_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/residence_proof/', verbose_name='Подтверждение места жительства'),
        ),
    ]
