# Generated by Django 5.2.11 on 2026-05-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_childapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childapplication',
            name='parent_passport_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/parent_passports/', verbose_name='Паспорт родителя'),
        ),
    ]
