# Generated by Django 5.2.11 on 2026-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_childapplication_parent_passport_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='parent_passport_file',
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='age_category',
            field=models.CharField(blank=True, choices=[('nursery_1_2', 'Ясельная (1-2 года)'), ('nursery_2_3', 'Ясельная (2-3 года)'), ('junior_3_4', 'Младшая (3-4 года)'), ('middle_4_5', 'Средняя (4-5 лет)'), ('senior_5_6', 'Старшая (5-6 лет)'), ('preparatory_6_7', 'Подготовительная (6-7 años)')], max_length=20, null=True, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='queuesettings',
            name='age_category',
            field=models.CharField(choices=[('nursery_1_2', 'Ясельная (1-2 года)'), ('nursery_2_3', 'Ясельная (2-3 года)'), ('junior_3_4', 'Младшая (3-4 года)'), ('middle_4_5', 'Средняя (4-5 лет)'), ('senior_5_6', 'Старшая (5-6 лет)'), ('preparatory_6_7', 'Подготовительная (6-7 años)')], max_length=20, unique=True, verbose_name='Возрастная категория'),
        ),
    ]
