# Generated by Django 5.2.11 on 2026-05-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_childapplication_age_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childapplication',
            name='child_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/child_photos/', verbose_name='Фотография ребенка'),
        ),
    ]
