# Generated by Django 5.2.11 on 2026-05-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_childapplication_child_photo'),
        ('children', '0004_remove_child_birth_certificate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childapplication',
            name='father_full_name',
        ),
        migrations.RemoveField(
            model_name='childapplication',
            name='father_phone',
        ),
        migrations.RemoveField(
            model_name='childapplication',
            name='legal_representative',
        ),
        migrations.RemoveField(
            model_name='childapplication',
            name='mother_full_name',
        ),
        migrations.RemoveField(
            model_name='childapplication',
            name='mother_phone',
        ),
        migrations.RemoveField(
            model_name='childapplication',
            name='passport_file',
        ),
        migrations.AddField(
            model_name='childapplication',
            name='applicant1_full_name',
            field=models.CharField(default='Не указано', max_length=200, verbose_name='ФИО заявителя (лицо, подписывающее документы)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childapplication',
            name='applicant1_is_primary',
            field=models.BooleanField(default=True, verbose_name='Основной заявитель'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='applicant1_passport_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/applicant1_passports/', verbose_name='Паспорт заявителя'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='applicant1_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон заявителя'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='applicant2_full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО второго заявителя'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='applicant2_passport_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/applicant2_passports/', verbose_name='Паспорт второго заявителя'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='applicant2_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон второго заявителя'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='child_snils_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/child_snils/', verbose_name='СНИЛС ребенка (скан)'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='insurance_policy_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/insurance/', verbose_name='Полис медицинского страхования'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='medical_card_a4_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/medical_cards_a4/', verbose_name='Медицинская карта ребенка (форма № 026/у) А4'),
        ),
        migrations.AddField(
            model_name='childapplication',
            name='sibling_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sibling_applications', to='children.child', verbose_name='Брат/сестра в детском саду'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='age_category',
            field=models.CharField(blank=True, choices=[('nursery_1_2', 'Первая младшая (1-2 года)'), ('nursery_2_3', 'Первая младшая (2-3 года)'), ('junior_3_4', 'Вторая младшая (3-4 года)'), ('middle_4_5', 'Средняя (4-5 лет)'), ('senior_5_6', 'Старшая (5-6 лет)'), ('preparatory_6_7', 'Подготовительная (6-7 лет)')], max_length=20, null=True, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='benefit_category',
            field=models.CharField(choices=[('extraordinary_sibling', 'Дети с внеочередным правом, братья/сёстры которых посещают тот же детский сад'), ('extraordinary', 'Дети с внеочередным правом на зачисление'), ('extraordinary_judge', 'Дети судей, сотрудников Следственного комитета или прокуратуры'), ('extraordinary_military_svo', 'Дети военнослужащих, добровольцев или сотрудников Росгвардии, погибших в ходе СВО'), ('extraordinary_chernobyl', 'Дети ликвидаторов аварии на Чернобыльской АЭС'), ('priority_sibling', 'Дети с первоочередным правом, братья/сёстры которых посещают тот же детский сад'), ('priority', 'Дети с первоочередным правом на зачисление'), ('priority_disability', 'Дети с инвалидностью'), ('priority_large_family', 'Дети многодетных родителей'), ('priority_parent_disability', 'Дети родителей с инвалидностью'), ('priority_military', 'Дети военнослужащих, в том числе участников СВО'), ('priority_police', 'Дети сотрудников полиции, ФСИН, ФССП, ФТС, ГПС'), ('preferential_sibling', 'Дети с преимущественным правом (брат/сестра уже посещает детский сад)'), ('preferential', 'Дети с преимущественным правом на зачисление'), ('none', 'Дети без льгот')], default='none', max_length=30, verbose_name='Категория льготы'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='child_snils',
            field=models.CharField(blank=True, max_length=20, verbose_name='СНИЛС ребенка (номер)'),
        ),
        migrations.AlterField(
            model_name='childapplication',
            name='vaccination_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/vaccinations/', verbose_name='Сертификат о прививках (форма № 063/у)'),
        ),
        migrations.AlterField(
            model_name='queuesettings',
            name='age_category',
            field=models.CharField(choices=[('nursery_1_2', 'Первая младшая (1-2 года)'), ('nursery_2_3', 'Первая младшая (2-3 года)'), ('junior_3_4', 'Вторая младшая (3-4 года)'), ('middle_4_5', 'Средняя (4-5 лет)'), ('senior_5_6', 'Старшая (5-6 лет)'), ('preparatory_6_7', 'Подготовительная (6-7 лет)')], max_length=20, unique=True, verbose_name='Возрастная категория'),
        ),
    ]
