# Generated by Django 5.2.11 on 2026-05-30 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен приглашения')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='staff.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Приглашение сотрудника',
                'verbose_name_plural': 'Приглашения сотрудников',
            },
        ),
    ]
