# Generated by Django 5.2.11 on 2026-05-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_employeeinvite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeInvite',
        ),
    ]
