# Generated by Django 5.2.11 on 2026-05-31 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_delete_employeeinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='absence_documents',
            field=models.JSONField(blank=True, default=dict, verbose_name='Документы отсутствия'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='staff.timesheet', verbose_name='Табель'),
        ),
    ]
