# Generated by Django 5.2.11 on 2026-04-24 19:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('child_full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО ребенка')),
                ('child_birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения ребенка')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата зачисления')),
                ('group_name', models.CharField(blank=True, help_text='Наименование группы при зачислении', max_length=100, null=True, verbose_name='Планируемая группа')),
                ('contract_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения договора')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания договора')),
                ('educational_program', models.TextField(blank=True, default='Основная общеобразовательная программа дошкольного образования муниципального бюджетного дошкольного образовательного учреждения Карабашский детский сад общеразвивающего вида №1 «Рябинушка» Бугульминского муниципального района Республики Татарстан', null=True, verbose_name='Образовательная программа')),
                ('study_period', models.IntegerField(default=5, verbose_name='Срок освоения программы (лет)')),
                ('stay_regimen', models.CharField(blank=True, default='пятидневная неделя (понедельник – пятница), 12 часов (с 6.00 до 18.00)', max_length=200, null=True, verbose_name='Режим пребывания')),
                ('parent_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Родительская плата (всего)')),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Абонентская плата')),
                ('food_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Питание')),
                ('basis_documents', models.TextField(blank=True, help_text='Документы, на основании которых заключен договор', null=True, verbose_name='Основание')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('draft', 'Сформирован'), ('signed', 'Подписан сторонами'), ('active', 'Действует'), ('terminated', 'Расторгнут'), ('expired', 'Истек')], default='draft', max_length=20, verbose_name='Статус договора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('director_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подписано заведующей')),
                ('parent_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подписано родителем')),
                ('generated_contract', models.FileField(blank=True, null=True, upload_to='contracts/generated/', verbose_name='Сгенерированный договор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='applications.childapplication', verbose_name='Заявление')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='children.child', verbose_name='Воспитанник')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.parentprofile', verbose_name='Родитель (законный представитель)')),
            ],
            options={
                'verbose_name': 'Договор об образовании',
                'verbose_name_plural': 'Договоры об образовании',
                'ordering': ['-registration_date', '-contract_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_number', models.CharField(max_length=50, unique=True, verbose_name='Номер в реестре')),
                ('has_additional_agreements', models.BooleanField(default=False, verbose_name='Есть дополнительные соглашения')),
                ('additional_agreements_info', models.TextField(blank=True, null=True, verbose_name='Информация о доп. соглашениях')),
                ('last_check_date', models.DateField(blank=True, null=True, verbose_name='Дата последней проверки')),
                ('check_notes', models.TextField(blank=True, null=True, verbose_name='Замечания при проверке')),
                ('storage_location', models.CharField(default='Личное дело воспитанника', max_length=100, verbose_name='Место хранения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registry_entry', to='contracts.educationcontract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Запись реестра договоров',
                'verbose_name_plural': 'Реестр договоров',
                'ordering': ['-registry_number'],
            },
        ),
        migrations.AddIndex(
            model_name='educationcontract',
            index=models.Index(fields=['contract_number'], name='contracts_e_contrac_476def_idx'),
        ),
        migrations.AddIndex(
            model_name='educationcontract',
            index=models.Index(fields=['status'], name='contracts_e_status_cd5063_idx'),
        ),
        migrations.AddIndex(
            model_name='educationcontract',
            index=models.Index(fields=['registration_date'], name='contracts_e_registr_9e74e7_idx'),
        ),
    ]
