# Generated by Django 5.2.11 on 2026-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcontract',
            name='child_gender',
            field=models.CharField(blank=True, choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1, null=True, verbose_name='Пол ребенка'),
        ),
    ]
