# Generated by Django 5.2.11 on 2026-04-24 19:12

import children.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО ребенка')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1, verbose_name='Пол')),
                ('birth_certificate', models.CharField(blank=True, help_text='Серия и номер свидетельства о рождении', max_length=100, verbose_name='Свидетельство о рождении')),
                ('birth_certificate_issued_by', models.CharField(blank=True, max_length=200, verbose_name='Кем выдано свидетельство')),
                ('birth_certificate_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи свидетельства')),
                ('medical_card_number', models.CharField(blank=True, max_length=50, verbose_name='Номер медицинской карты')),
                ('policy_oms_number', models.CharField(blank=True, max_length=50, verbose_name='Полис ОМС')),
                ('snils', models.CharField(blank=True, max_length=50, verbose_name='СНИЛС')),
                ('blood_type', models.CharField(blank=True, max_length=3, verbose_name='Группа крови')),
                ('allergies', models.TextField(blank=True, verbose_name='Аллергии')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='Хронические заболевания')),
                ('special_needs', models.TextField(blank=True, verbose_name='Особые потребности')),
                ('disability_certificate', models.CharField(blank=True, max_length=100, verbose_name='Справка об инвалидности')),
                ('registration_address', models.TextField(verbose_name='Адрес регистрации')),
                ('actual_address', models.TextField(verbose_name='Фактический адрес проживания')),
                ('photo', models.ImageField(blank=True, help_text='Рекомендуемый размер: 300x300 пикселей', null=True, upload_to=children.models.child_photo_path, verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен в системе')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Дата зачисления')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='documents/registration/', verbose_name='Свидетельство о регистрации')),
                ('registration_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи регистрации')),
                ('medical_card_file', models.FileField(blank=True, null=True, upload_to='documents/medical/', verbose_name='Медицинская карта (файл)')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку ПД')),
                ('consent_photo_video', models.BooleanField(default=False, verbose_name='Согласие на фото/видео')),
                ('consent_medical_intervention', models.BooleanField(default=False, verbose_name='Согласие на медвмешательство')),
                ('consent_data_processing_date', models.DateField(blank=True, null=True)),
                ('consent_photo_video_date', models.DateField(blank=True, null=True)),
                ('consent_medical_intervention_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_record', to='applications.childapplication', verbose_name='Заявление о приеме')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ChildParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('grandmother', 'Бабушка'), ('grandfather', 'Дедушка'), ('guardian', 'Опекун')], max_length=15, verbose_name='Родство')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='children.child', verbose_name='Ребенок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='accounts.parentprofile', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Связь ребенок-родитель',
                'verbose_name_plural': 'Связи ребенок-родитель',
                'unique_together': {('child', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='children.ChildParent', to='accounts.parentprofile', verbose_name='Родители'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('age_category', models.CharField(choices=[('nursery', 'Ясельная (1.5-3 года)'), ('junior', 'Младшая (3-4 года)'), ('middle', 'Средняя (4-5 лет)'), ('senior', 'Старшая (5-6 лет)'), ('preparatory', 'Подготовительная (6-7 лет)')], max_length=20, verbose_name='Возрастная категория')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Вместимость')),
                ('room_number', models.CharField(blank=True, max_length=10, verbose_name='Номер комнаты')),
                ('current_count', models.PositiveIntegerField(default=0, verbose_name='Текущее количество детей')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Воспитатель')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.group', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='PersonalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('archived', 'В архиве'), ('graduated', 'Выпущен'), ('transferred', 'Переведен')], default='active', max_length=20)),
                ('registration_expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия регистрации')),
                ('medical_card_expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия медкарты')),
                ('policy_expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия полиса')),
                ('notification_sent_registration', models.BooleanField(default=False)),
                ('notification_sent_medical', models.BooleanField(default=False)),
                ('notification_sent_policy', models.BooleanField(default=False)),
                ('additional_documents', models.JSONField(default=list, verbose_name='Дополнительные документы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_files', to='children.child')),
            ],
            options={
                'verbose_name': 'Личное дело',
                'verbose_name_plural': 'Личные дела',
            },
        ),
        migrations.CreateModel(
            name='DocumentCheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('registration_valid', models.BooleanField(default=False)),
                ('medical_valid', models.BooleanField(default=False)),
                ('policy_valid', models.BooleanField(default=False)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_history', to='children.personalfile')),
            ],
            options={
                'verbose_name': 'История проверки',
                'verbose_name_plural': 'Истории проверок',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='child',
            name='personal_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_record', to='children.personalfile'),
        ),
    ]
