# Generated by Django 5.2.11 on 2026-04-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parents',
        ),
        migrations.AlterField(
            model_name='childparent',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='children.child'),
        ),
        migrations.AlterField(
            model_name='childparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='accounts.parentprofile'),
        ),
    ]
