# Generated by Django 5.2.11 on 2026-05-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_remove_child_parents_alter_childparent_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birth_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/birth_certificates/', verbose_name='Свидетельство о рождении (скан-копия)'),
        ),
        migrations.AddField(
            model_name='child',
            name='disability',
            field=models.BooleanField(default=False, verbose_name='Инвалидность'),
        ),
        migrations.AddField(
            model_name='child',
            name='health_group',
            field=models.CharField(blank=True, choices=[('1', 'I группа - здоровые'), ('2', 'II группа - с функциональными отклонениями'), ('3', 'III группа - хронические заболевания в компенсации'), ('4', 'IV группа - хронические заболевания в субкомпенсации'), ('5', 'V группа - хронические заболевания в декомпенсации')], max_length=20, verbose_name='Группа здоровья'),
        ),
        migrations.AddField(
            model_name='child',
            name='vaccination_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/vaccinations/', verbose_name='Прививочная карта'),
        ),
    ]
