# Generated by Django 5.2.11 on 2026-05-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_birth_certificate_file_child_disability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='birth_certificate_file',
        ),
        migrations.RemoveField(
            model_name='child',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='child',
            name='health_group',
        ),
        migrations.RemoveField(
            model_name='child',
            name='vaccination_card',
        ),
    ]
