# Generated by Django 5.2.11 on 2026-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_remove_child_birth_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birth_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='children/birth_certificates/', verbose_name='Скан свидетельства о рождении'),
        ),
        migrations.AddField(
            model_name='child',
            name='has_vaccinations',
            field=models.BooleanField(default=False, verbose_name='Наличие прививок'),
        ),
        migrations.AddField(
            model_name='child',
            name='insurance_policy_file',
            field=models.FileField(blank=True, null=True, upload_to='children/insurance/', verbose_name='Скан полиса ОМС'),
        ),
        migrations.AddField(
            model_name='child',
            name='pmpk_conclusion',
            field=models.FileField(blank=True, null=True, upload_to='children/pmpk/', verbose_name='Заключение ПМПК'),
        ),
        migrations.AddField(
            model_name='child',
            name='snils_file',
            field=models.FileField(blank=True, null=True, upload_to='children/snils/', verbose_name='Скан СНИЛС'),
        ),
        migrations.AddField(
            model_name='child',
            name='vaccination_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='children/vaccinations/', verbose_name='Скан прививочного сертификата'),
        ),
    ]
