# Generated by Django 5.2.11 on 2026-04-24 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Полдник'), ('dinner', 'Ужин')], max_length=20, verbose_name='Тип питания')),
                ('dish_name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('calories', models.IntegerField(verbose_name='Калории')),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Белки (г)')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Жиры (г)')),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Углеводы (г)')),
                ('weight', models.IntegerField(verbose_name='Вес (г)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утверждено')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Утвердил(а)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['group', 'day_of_week', 'meal_type'],
                'unique_together': {('group', 'day_of_week', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='ChildMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('eaten', models.BooleanField(default=False, verbose_name='Съедено')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child', verbose_name='Ребенок')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Питание ребенка',
                'verbose_name_plural': 'Питание детей',
                'unique_together': {('child', 'menu', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenuPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='Начало недели')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утверждено')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Утвердил(а)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'План меню на неделю',
                'verbose_name_plural': 'Планы меню на неделю',
                'unique_together': {('group', 'week_start_date')},
            },
        ),
    ]
