# Generated by Django 5.2.11 on 2026-04-24 19:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('children', '0001_initial'),
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер приказа')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Дата приказа')),
                ('order_type', models.CharField(choices=[('enrollment', 'О зачислении'), ('transfer', 'О переводе'), ('expulsion', 'Об отчислении')], default='enrollment', max_length=20, verbose_name='Тип приказа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Издан'), ('executed', 'Исполнен')], default='draft', max_length=20, verbose_name='Статус приказа')),
                ('basis_documents', models.TextField(help_text='Перечень документов, на основании которых издается приказ', verbose_name='Основание')),
                ('enrollment_date', models.DateField(verbose_name='Дата зачисления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_orders', to='applications.childapplication', verbose_name='Заявление')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.child', verbose_name='Ребенок')),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_order', to='contracts.educationcontract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заведующая')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Приказ о зачислении',
                'verbose_name_plural': 'Приказы о зачислении',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
    ]
