# Generated by Django 5.2.11 on 2026-04-24 19:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_group', models.CharField(choices=[('nursery', 'Ясельная (1.5-3 года)'), ('junior', 'Младшая (3-4 года)'), ('middle', 'Средняя (4-5 лет)'), ('senior', 'Старшая (5-6 лет)'), ('preparatory', 'Подготовительная (6-7 лет)')], max_length=15, verbose_name='Возрастная группа')),
                ('lesson_type', models.CharField(choices=[('cognitive', 'Познавательное'), ('creative', 'Творческое'), ('physical', 'Физкультурное'), ('music', 'Музыкальное'), ('language', 'Речевое развитие'), ('math', 'Математическое'), ('environment', 'Окружающий мир'), ('safety', 'Безопасность'), ('social', 'Социально-коммуникативное')], max_length=20, verbose_name='Тип занятия')),
                ('objectives', models.TextField(verbose_name='Цели и задачи')),
                ('materials', models.TextField(verbose_name='Материалы')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность (мин)')),
                ('steps', models.TextField(verbose_name='Этапы проведения')),
                ('variations', models.TextField(blank=True, verbose_name='Вариации и дополнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='Общедоступный шаблон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Шаблон занятия',
                'verbose_name_plural': 'Шаблоны занятий',
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название занятия')),
                ('lesson_type', models.CharField(choices=[('cognitive', 'Познавательное'), ('creative', 'Творческое'), ('physical', 'Физкультурное'), ('music', 'Музыкальное'), ('language', 'Речевое развитие'), ('math', 'Математическое'), ('environment', 'Окружающий мир'), ('safety', 'Безопасность'), ('social', 'Социально-коммуникативное')], max_length=20, verbose_name='Тип занятия')),
                ('description', models.TextField(verbose_name='Описание занятия')),
                ('objectives', models.TextField(verbose_name='Цели и задачи')),
                ('materials', models.TextField(blank=True, verbose_name='Необходимые материалы')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Продолжительность (мин)')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкое'), ('medium', 'Среднее'), ('hard', 'Сложное')], max_length=10, verbose_name='Сложность')),
                ('age_appropriate', models.BooleanField(default=True, verbose_name='Соответствует возрасту')),
                ('planned_date', models.DateField(verbose_name='Планируемая дата')),
                ('planned_time', models.TimeField(verbose_name='Планируемое время')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('actual_time', models.TimeField(blank=True, null=True, verbose_name='Фактическое время')),
                ('completed', models.BooleanField(default=False, verbose_name='Проведено')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки о проведении')),
                ('success_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка успешности (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Воспитатель')),
            ],
            options={
                'verbose_name': 'План занятия',
                'verbose_name_plural': 'Планы занятий',
                'ordering': ['-planned_date', 'planned_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок напоминания')),
                ('reminder_type', models.CharField(choices=[('preparation', 'Подготовка к занятию'), ('materials', 'Подготовка материалов'), ('parent_meeting', 'Родительское собрание'), ('event', 'Мероприятие'), ('other', 'Другое')], max_length=20, verbose_name='Тип напоминания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('due_date', models.DateField(verbose_name='Срок выполнения')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('priority', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Приоритет (1-высокий, 3-низкий)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.group', verbose_name='Группа')),
                ('lesson_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessonplan', verbose_name='Связанное занятие')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Воспитатель')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['due_date', 'due_time', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('activity_type', models.CharField(max_length=50, verbose_name='Вид деятельности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_regular', models.BooleanField(default=True, verbose_name='Регулярное занятие')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('group', 'day_of_week', 'start_time')},
            },
        ),
    ]
