# Generated by Django 5.2.11 on 2026-04-24 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала посещения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания посещения')),
                ('day_1', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_2', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_3', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_4', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_5', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_6', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_7', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_8', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_9', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_10', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_11', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_12', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_13', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_14', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_15', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_16', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_17', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_18', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_19', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_20', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_21', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_22', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_23', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_24', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_25', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_26', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_27', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_28', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_29', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_30', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('day_31', models.CharField(blank=True, choices=[('', '-'), ('present', 'Я'), ('absent_unexcused', 'НЯ'), ('absent_sick', 'НБ'), ('absent_vacation', 'НУ'), ('weekend', 'В')], default='', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
            },
        ),
        migrations.CreateModel(
            name='AbsenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sick_leave', 'Больничный лист'), ('medical_certificate', 'Медицинская справка'), ('parent_statement', 'Заявление родителя'), ('sanatorium_voucher', 'Путевка в санаторий'), ('other', 'Другое')], max_length=50, verbose_name='Тип документа')),
                ('document_file', models.FileField(upload_to='absence_documents/%Y/%m/', verbose_name='Файл документа')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='attendance.attendancerecord', verbose_name='Запись посещаемости')),
            ],
            options={
                'verbose_name': 'Документ отсутствия',
                'verbose_name_plural': 'Документы отсутствия',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утвержден')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sheets', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил (заведующая)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sheets', to=settings.AUTH_USER_MODEL, verbose_name='Создал (воспитатель)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Табель посещаемости',
                'verbose_name_plural': 'Табели посещаемости',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesheet', verbose_name='Табель'),
        ),
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Выходной/Праздник')),
                ('holiday_name', models.CharField(blank=True, max_length=100, verbose_name='Название праздника')),
                ('is_working_saturday', models.BooleanField(default=False, verbose_name='Рабочая суббота')),
            ],
            options={
                'verbose_name': 'Производственный календарь',
                'verbose_name_plural': 'Производственный календарь',
                'ordering': ['date'],
                'unique_together': {('year', 'date')},
            },
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='production_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.productioncalendar', verbose_name='Производственный календарь'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('sheet', 'child')},
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Полдник'), ('dinner', 'Ужин')], max_length=20)),
                ('eaten', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='children.child')),
            ],
            options={
                'verbose_name': 'Питание',
                'verbose_name_plural': 'Питание',
                'db_table': 'attendance_meal',
                'unique_together': {('child', 'date', 'meal_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendancesheet',
            unique_together={('group', 'month', 'year')},
        ),
    ]
